//! THIS FILE IS AUTOMATICALLY GENERATED; do not modify!

const std = @import("std");

pub const google = struct {
    pub const protobuf = struct {
        pub const compiler = struct {
            pub const Version = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .major = 1,
                        .minor = 2,
                        .patch = 3,
                        .suffix = 4,
                    },
                };

                major: ?i32 = null,
                minor: ?i32 = null,
                patch: ?i32 = null,
                suffix: ?[]const u8 = null,
            };

            pub const CodeGeneratorRequest = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .file_to_generate = 1,
                        .parameter = 2,
                        .proto_file = 15,
                        .compiler_version = 3,
                    },
                };

                file_to_generate: std.ArrayListUnmanaged([]const u8) = .{},
                parameter: ?[]const u8 = null,
                proto_file: std.ArrayListUnmanaged(google.protobuf.FileDescriptorProto) = .{},
                compiler_version: ?google.protobuf.compiler.Version = null,
            };

            pub const CodeGeneratorResponse = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .@"error" = 1,
                        .supported_features = 2,
                        .file = 15,
                    },
                };

                pub const Feature = enum(i32) {
                    pub const protobuf_metadata = .{
                        .syntax = .proto2,
                    };

                    FEATURE_NONE = 0,
                    FEATURE_PROTO3_OPTIONAL = 1,
                };

                pub const File = struct {
                    pub const protobuf_metadata = .{
                        .syntax = .proto2,
                        .field_numbers = .{
                            .name = 1,
                            .insertion_point = 2,
                            .content = 15,
                            .generated_code_info = 16,
                        },
                    };

                    name: ?[]const u8 = null,
                    insertion_point: ?[]const u8 = null,
                    content: ?[]const u8 = null,
                    generated_code_info: ?google.protobuf.GeneratedCodeInfo = null,
                };

                @"error": ?[]const u8 = null,
                supported_features: ?u64 = null,
                file: std.ArrayListUnmanaged(google.protobuf.compiler.CodeGeneratorResponse.File) = .{},
            };
        };

        pub const Any = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .type_url = 1,
                    .value = 2,
                },
            };

            type_url: []const u8 = "",
            value: []const u8 = "",
        };

        pub const Api = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .methods = 2,
                    .options = 3,
                    .version = 4,
                    .source_context = 5,
                    .mixins = 6,
                    .syntax = 7,
                },
            };

            name: []const u8 = "",
            methods: std.ArrayListUnmanaged(google.protobuf.Method) = .{},
            options: std.ArrayListUnmanaged(google.protobuf.Option) = .{},
            version: []const u8 = "",
            source_context: google.protobuf.SourceContext = .{},
            mixins: std.ArrayListUnmanaged(google.protobuf.Mixin) = .{},
            syntax: google.protobuf.Syntax = @enumFromInt(0),
        };

        pub const Method = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .request_type_url = 2,
                    .request_streaming = 3,
                    .response_type_url = 4,
                    .response_streaming = 5,
                    .options = 6,
                    .syntax = 7,
                },
            };

            name: []const u8 = "",
            request_type_url: []const u8 = "",
            request_streaming: bool = false,
            response_type_url: []const u8 = "",
            response_streaming: bool = false,
            options: std.ArrayListUnmanaged(google.protobuf.Option) = .{},
            syntax: google.protobuf.Syntax = @enumFromInt(0),
        };

        pub const Mixin = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .root = 2,
                },
            };

            name: []const u8 = "",
            root: []const u8 = "",
        };

        pub const FileDescriptorSet = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .file = 1,
                },
            };

            file: std.ArrayListUnmanaged(google.protobuf.FileDescriptorProto) = .{},
        };

        pub const FileDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .package = 2,
                    .dependency = 3,
                    .public_dependency = 10,
                    .weak_dependency = 11,
                    .message_type = 4,
                    .enum_type = 5,
                    .service = 6,
                    .extension = 7,
                    .options = 8,
                    .source_code_info = 9,
                    .syntax = 12,
                    .edition = 13,
                },
            };

            name: ?[]const u8 = null,
            package: ?[]const u8 = null,
            dependency: std.ArrayListUnmanaged([]const u8) = .{},
            public_dependency: std.ArrayListUnmanaged(i32) = .{},
            weak_dependency: std.ArrayListUnmanaged(i32) = .{},
            message_type: std.ArrayListUnmanaged(google.protobuf.DescriptorProto) = .{},
            enum_type: std.ArrayListUnmanaged(google.protobuf.EnumDescriptorProto) = .{},
            service: std.ArrayListUnmanaged(google.protobuf.ServiceDescriptorProto) = .{},
            extension: std.ArrayListUnmanaged(google.protobuf.FieldDescriptorProto) = .{},
            options: ?google.protobuf.FileOptions = null,
            source_code_info: ?google.protobuf.SourceCodeInfo = null,
            syntax: ?[]const u8 = null,
            edition: ?[]const u8 = null,
        };

        pub const DescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .field = 2,
                    .extension = 6,
                    .nested_type = 3,
                    .enum_type = 4,
                    .extension_range = 5,
                    .oneof_decl = 8,
                    .options = 7,
                    .reserved_range = 9,
                    .reserved_name = 10,
                },
            };

            pub const ExtensionRange = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .start = 1,
                        .end = 2,
                        .options = 3,
                    },
                };

                start: ?i32 = null,
                end: ?i32 = null,
                options: ?google.protobuf.ExtensionRangeOptions = null,
            };

            pub const ReservedRange = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .start = 1,
                        .end = 2,
                    },
                };

                start: ?i32 = null,
                end: ?i32 = null,
            };

            name: ?[]const u8 = null,
            field: std.ArrayListUnmanaged(google.protobuf.FieldDescriptorProto) = .{},
            extension: std.ArrayListUnmanaged(google.protobuf.FieldDescriptorProto) = .{},
            nested_type: std.ArrayListUnmanaged(google.protobuf.DescriptorProto) = .{},
            enum_type: std.ArrayListUnmanaged(google.protobuf.EnumDescriptorProto) = .{},
            extension_range: std.ArrayListUnmanaged(google.protobuf.DescriptorProto.ExtensionRange) = .{},
            oneof_decl: std.ArrayListUnmanaged(google.protobuf.OneofDescriptorProto) = .{},
            options: ?google.protobuf.MessageOptions = null,
            reserved_range: std.ArrayListUnmanaged(google.protobuf.DescriptorProto.ReservedRange) = .{},
            reserved_name: std.ArrayListUnmanaged([]const u8) = .{},
        };

        pub const ExtensionRangeOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .uninterpreted_option = 999,
                },
            };

            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const FieldDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .number = 3,
                    .label = 4,
                    .type = 5,
                    .type_name = 6,
                    .extendee = 2,
                    .default_value = 7,
                    .oneof_index = 9,
                    .json_name = 10,
                    .options = 8,
                    .proto3_optional = 17,
                },
            };

            pub const Type = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                TYPE_DOUBLE = 1,
                TYPE_FLOAT = 2,
                TYPE_INT64 = 3,
                TYPE_UINT64 = 4,
                TYPE_INT32 = 5,
                TYPE_FIXED64 = 6,
                TYPE_FIXED32 = 7,
                TYPE_BOOL = 8,
                TYPE_STRING = 9,
                TYPE_GROUP = 10,
                TYPE_MESSAGE = 11,
                TYPE_BYTES = 12,
                TYPE_UINT32 = 13,
                TYPE_ENUM = 14,
                TYPE_SFIXED32 = 15,
                TYPE_SFIXED64 = 16,
                TYPE_SINT32 = 17,
                TYPE_SINT64 = 18,
            };

            pub const Label = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                LABEL_OPTIONAL = 1,
                LABEL_REQUIRED = 2,
                LABEL_REPEATED = 3,
            };

            name: ?[]const u8 = null,
            number: ?i32 = null,
            label: ?google.protobuf.FieldDescriptorProto.Label = null,
            type: ?google.protobuf.FieldDescriptorProto.Type = null,
            type_name: ?[]const u8 = null,
            extendee: ?[]const u8 = null,
            default_value: ?[]const u8 = null,
            oneof_index: ?i32 = null,
            json_name: ?[]const u8 = null,
            options: ?google.protobuf.FieldOptions = null,
            proto3_optional: ?bool = null,
        };

        pub const OneofDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .options = 2,
                },
            };

            name: ?[]const u8 = null,
            options: ?google.protobuf.OneofOptions = null,
        };

        pub const EnumDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .value = 2,
                    .options = 3,
                    .reserved_range = 4,
                    .reserved_name = 5,
                },
            };

            pub const EnumReservedRange = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .start = 1,
                        .end = 2,
                    },
                };

                start: ?i32 = null,
                end: ?i32 = null,
            };

            name: ?[]const u8 = null,
            value: std.ArrayListUnmanaged(google.protobuf.EnumValueDescriptorProto) = .{},
            options: ?google.protobuf.EnumOptions = null,
            reserved_range: std.ArrayListUnmanaged(google.protobuf.EnumDescriptorProto.EnumReservedRange) = .{},
            reserved_name: std.ArrayListUnmanaged([]const u8) = .{},
        };

        pub const EnumValueDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .number = 2,
                    .options = 3,
                },
            };

            name: ?[]const u8 = null,
            number: ?i32 = null,
            options: ?google.protobuf.EnumValueOptions = null,
        };

        pub const ServiceDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .method = 2,
                    .options = 3,
                },
            };

            name: ?[]const u8 = null,
            method: std.ArrayListUnmanaged(google.protobuf.MethodDescriptorProto) = .{},
            options: ?google.protobuf.ServiceOptions = null,
        };

        pub const MethodDescriptorProto = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 1,
                    .input_type = 2,
                    .output_type = 3,
                    .options = 4,
                    .client_streaming = 5,
                    .server_streaming = 6,
                },
            };

            name: ?[]const u8 = null,
            input_type: ?[]const u8 = null,
            output_type: ?[]const u8 = null,
            options: ?google.protobuf.MethodOptions = null,
            client_streaming: ?bool = null,
            server_streaming: ?bool = null,
        };

        pub const FileOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .java_package = 1,
                    .java_outer_classname = 8,
                    .java_multiple_files = 10,
                    .java_generate_equals_and_hash = 20,
                    .java_string_check_utf8 = 27,
                    .optimize_for = 9,
                    .go_package = 11,
                    .cc_generic_services = 16,
                    .java_generic_services = 17,
                    .py_generic_services = 18,
                    .php_generic_services = 42,
                    .deprecated = 23,
                    .cc_enable_arenas = 31,
                    .objc_class_prefix = 36,
                    .csharp_namespace = 37,
                    .swift_prefix = 39,
                    .php_class_prefix = 40,
                    .php_namespace = 41,
                    .php_metadata_namespace = 44,
                    .ruby_package = 45,
                    .uninterpreted_option = 999,
                },
            };

            pub const OptimizeMode = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                SPEED = 1,
                CODE_SIZE = 2,
                LITE_RUNTIME = 3,
            };

            java_package: ?[]const u8 = null,
            java_outer_classname: ?[]const u8 = null,
            java_multiple_files: ?bool = null,
            java_generate_equals_and_hash: ?bool = null,
            java_string_check_utf8: ?bool = null,
            optimize_for: ?google.protobuf.FileOptions.OptimizeMode = null,
            go_package: ?[]const u8 = null,
            cc_generic_services: ?bool = null,
            java_generic_services: ?bool = null,
            py_generic_services: ?bool = null,
            php_generic_services: ?bool = null,
            deprecated: ?bool = null,
            cc_enable_arenas: ?bool = null,
            objc_class_prefix: ?[]const u8 = null,
            csharp_namespace: ?[]const u8 = null,
            swift_prefix: ?[]const u8 = null,
            php_class_prefix: ?[]const u8 = null,
            php_namespace: ?[]const u8 = null,
            php_metadata_namespace: ?[]const u8 = null,
            ruby_package: ?[]const u8 = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const MessageOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .message_set_wire_format = 1,
                    .no_standard_descriptor_accessor = 2,
                    .deprecated = 3,
                    .map_entry = 7,
                    .deprecated_legacy_json_field_conflicts = 11,
                    .uninterpreted_option = 999,
                },
            };

            message_set_wire_format: ?bool = null,
            no_standard_descriptor_accessor: ?bool = null,
            deprecated: ?bool = null,
            map_entry: ?bool = null,
            deprecated_legacy_json_field_conflicts: ?bool = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const FieldOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .ctype = 1,
                    .@"packed" = 2,
                    .jstype = 6,
                    .lazy = 5,
                    .unverified_lazy = 15,
                    .deprecated = 3,
                    .weak = 10,
                    .debug_redact = 16,
                    .retention = 17,
                    .target = 18,
                    .uninterpreted_option = 999,
                },
            };

            pub const CType = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                STRING = 0,
                CORD = 1,
                STRING_PIECE = 2,
            };

            pub const JSType = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                JS_NORMAL = 0,
                JS_STRING = 1,
                JS_NUMBER = 2,
            };

            pub const OptionRetention = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                RETENTION_UNKNOWN = 0,
                RETENTION_RUNTIME = 1,
                RETENTION_SOURCE = 2,
            };

            pub const OptionTargetType = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                TARGET_TYPE_UNKNOWN = 0,
                TARGET_TYPE_FILE = 1,
                TARGET_TYPE_EXTENSION_RANGE = 2,
                TARGET_TYPE_MESSAGE = 3,
                TARGET_TYPE_FIELD = 4,
                TARGET_TYPE_ONEOF = 5,
                TARGET_TYPE_ENUM = 6,
                TARGET_TYPE_ENUM_ENTRY = 7,
                TARGET_TYPE_SERVICE = 8,
                TARGET_TYPE_METHOD = 9,
            };

            ctype: ?google.protobuf.FieldOptions.CType = null,
            @"packed": ?bool = null,
            jstype: ?google.protobuf.FieldOptions.JSType = null,
            lazy: ?bool = null,
            unverified_lazy: ?bool = null,
            deprecated: ?bool = null,
            weak: ?bool = null,
            debug_redact: ?bool = null,
            retention: ?google.protobuf.FieldOptions.OptionRetention = null,
            target: ?google.protobuf.FieldOptions.OptionTargetType = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const OneofOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .uninterpreted_option = 999,
                },
            };

            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const EnumOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .allow_alias = 2,
                    .deprecated = 3,
                    .deprecated_legacy_json_field_conflicts = 6,
                    .uninterpreted_option = 999,
                },
            };

            allow_alias: ?bool = null,
            deprecated: ?bool = null,
            deprecated_legacy_json_field_conflicts: ?bool = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const EnumValueOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .deprecated = 1,
                    .uninterpreted_option = 999,
                },
            };

            deprecated: ?bool = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const ServiceOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .deprecated = 33,
                    .uninterpreted_option = 999,
                },
            };

            deprecated: ?bool = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const MethodOptions = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .deprecated = 33,
                    .idempotency_level = 34,
                    .uninterpreted_option = 999,
                },
            };

            pub const IdempotencyLevel = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                };

                IDEMPOTENCY_UNKNOWN = 0,
                NO_SIDE_EFFECTS = 1,
                IDEMPOTENT = 2,
            };

            deprecated: ?bool = null,
            idempotency_level: ?google.protobuf.MethodOptions.IdempotencyLevel = null,
            uninterpreted_option: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption) = .{},
        };

        pub const UninterpretedOption = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .name = 2,
                    .identifier_value = 3,
                    .positive_int_value = 4,
                    .negative_int_value = 5,
                    .double_value = 6,
                    .string_value = 7,
                    .aggregate_value = 8,
                },
            };

            pub const NamePart = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .name_part = 1,
                        .is_extension = 2,
                    },
                };

                name_part: []const u8 = "",
                is_extension: bool = false,
            };

            name: std.ArrayListUnmanaged(google.protobuf.UninterpretedOption.NamePart) = .{},
            identifier_value: ?[]const u8 = null,
            positive_int_value: ?u64 = null,
            negative_int_value: ?i64 = null,
            double_value: ?f64 = null,
            string_value: ?[]const u8 = null,
            aggregate_value: ?[]const u8 = null,
        };

        pub const SourceCodeInfo = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .location = 1,
                },
            };

            pub const Location = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .path = 1,
                        .span = 2,
                        .leading_comments = 3,
                        .trailing_comments = 4,
                        .leading_detached_comments = 6,
                    },
                };

                path: std.ArrayListUnmanaged(i32) = .{},
                span: std.ArrayListUnmanaged(i32) = .{},
                leading_comments: ?[]const u8 = null,
                trailing_comments: ?[]const u8 = null,
                leading_detached_comments: std.ArrayListUnmanaged([]const u8) = .{},
            };

            location: std.ArrayListUnmanaged(google.protobuf.SourceCodeInfo.Location) = .{},
        };

        pub const GeneratedCodeInfo = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto2,
                .field_numbers = .{
                    .annotation = 1,
                },
            };

            pub const Annotation = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto2,
                    .field_numbers = .{
                        .path = 1,
                        .source_file = 2,
                        .begin = 3,
                        .end = 4,
                        .semantic = 5,
                    },
                };

                pub const Semantic = enum(i32) {
                    pub const protobuf_metadata = .{
                        .syntax = .proto2,
                    };

                    NONE = 0,
                    SET = 1,
                    ALIAS = 2,
                };

                path: std.ArrayListUnmanaged(i32) = .{},
                source_file: ?[]const u8 = null,
                begin: ?i32 = null,
                end: ?i32 = null,
                semantic: ?google.protobuf.GeneratedCodeInfo.Annotation.Semantic = null,
            };

            annotation: std.ArrayListUnmanaged(google.protobuf.GeneratedCodeInfo.Annotation) = .{},
        };

        pub const Duration = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .seconds = 1,
                    .nanos = 2,
                },
            };

            seconds: i64 = 0,
            nanos: i32 = 0,
        };

        pub const Empty = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{},
            };
        };

        pub const FieldMask = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .paths = 1,
                },
            };

            paths: std.ArrayListUnmanaged([]const u8) = .{},
        };

        pub const SourceContext = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .file_name = 1,
                },
            };

            file_name: []const u8 = "",
        };

        pub const Struct = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{},
            };

            fields: std.AutoArrayHashMapUnmanaged([]const u8, google.protobuf.Value) = .{},
        };

        pub const Value = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{},
            };
        };

        pub const NullValue = enum(i32) {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
            };

            NULL_VALUE = 0,
        };

        pub const ListValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .values = 1,
                },
            };

            values: std.ArrayListUnmanaged(google.protobuf.Value) = .{},
        };

        pub const Timestamp = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .seconds = 1,
                    .nanos = 2,
                },
            };

            seconds: i64 = 0,
            nanos: i32 = 0,
        };

        pub const Type = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .fields = 2,
                    .oneofs = 3,
                    .options = 4,
                    .source_context = 5,
                    .syntax = 6,
                },
            };

            name: []const u8 = "",
            fields: std.ArrayListUnmanaged(google.protobuf.Field) = .{},
            oneofs: std.ArrayListUnmanaged([]const u8) = .{},
            options: std.ArrayListUnmanaged(google.protobuf.Option) = .{},
            source_context: google.protobuf.SourceContext = .{},
            syntax: google.protobuf.Syntax = @enumFromInt(0),
        };

        pub const Field = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .kind = 1,
                    .cardinality = 2,
                    .number = 3,
                    .name = 4,
                    .type_url = 6,
                    .oneof_index = 7,
                    .@"packed" = 8,
                    .options = 9,
                    .json_name = 10,
                    .default_value = 11,
                },
            };

            pub const Kind = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto3,
                };

                TYPE_UNKNOWN = 0,
                TYPE_DOUBLE = 1,
                TYPE_FLOAT = 2,
                TYPE_INT64 = 3,
                TYPE_UINT64 = 4,
                TYPE_INT32 = 5,
                TYPE_FIXED64 = 6,
                TYPE_FIXED32 = 7,
                TYPE_BOOL = 8,
                TYPE_STRING = 9,
                TYPE_GROUP = 10,
                TYPE_MESSAGE = 11,
                TYPE_BYTES = 12,
                TYPE_UINT32 = 13,
                TYPE_ENUM = 14,
                TYPE_SFIXED32 = 15,
                TYPE_SFIXED64 = 16,
                TYPE_SINT32 = 17,
                TYPE_SINT64 = 18,
            };

            pub const Cardinality = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto3,
                };

                CARDINALITY_UNKNOWN = 0,
                CARDINALITY_OPTIONAL = 1,
                CARDINALITY_REQUIRED = 2,
                CARDINALITY_REPEATED = 3,
            };

            kind: google.protobuf.Field.Kind = @enumFromInt(0),
            cardinality: google.protobuf.Field.Cardinality = @enumFromInt(0),
            number: i32 = 0,
            name: []const u8 = "",
            type_url: []const u8 = "",
            oneof_index: i32 = 0,
            @"packed": bool = false,
            options: std.ArrayListUnmanaged(google.protobuf.Option) = .{},
            json_name: []const u8 = "",
            default_value: []const u8 = "",
        };

        pub const Enum = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .enumvalue = 2,
                    .options = 3,
                    .source_context = 4,
                    .syntax = 5,
                },
            };

            name: []const u8 = "",
            enumvalue: std.ArrayListUnmanaged(google.protobuf.EnumValue) = .{},
            options: std.ArrayListUnmanaged(google.protobuf.Option) = .{},
            source_context: google.protobuf.SourceContext = .{},
            syntax: google.protobuf.Syntax = @enumFromInt(0),
        };

        pub const EnumValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .number = 2,
                    .options = 3,
                },
            };

            name: []const u8 = "",
            number: i32 = 0,
            options: std.ArrayListUnmanaged(google.protobuf.Option) = .{},
        };

        pub const Option = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .name = 1,
                    .value = 2,
                },
            };

            name: []const u8 = "",
            value: google.protobuf.Any = .{},
        };

        pub const Syntax = enum(i32) {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
            };

            SYNTAX_PROTO2 = 0,
            SYNTAX_PROTO3 = 1,
        };

        pub const DoubleValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: f64 = 0,
        };

        pub const FloatValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: f32 = 0,
        };

        pub const Int64Value = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: i64 = 0,
        };

        pub const UInt64Value = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: u64 = 0,
        };

        pub const Int32Value = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: i32 = 0,
        };

        pub const UInt32Value = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: u32 = 0,
        };

        pub const BoolValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: bool = false,
        };

        pub const StringValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: []const u8 = "",
        };

        pub const BytesValue = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .value = 1,
                },
            };

            value: []const u8 = "",
        };
    };
};

pub const protobuf_test_messages = struct {
    pub const proto3 = struct {
        pub const TestAllTypesProto3 = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .optional_int32 = 1,
                    .optional_int64 = 2,
                    .optional_uint32 = 3,
                    .optional_uint64 = 4,
                    .optional_sint32 = 5,
                    .optional_sint64 = 6,
                    .optional_fixed32 = 7,
                    .optional_fixed64 = 8,
                    .optional_sfixed32 = 9,
                    .optional_sfixed64 = 10,
                    .optional_float = 11,
                    .optional_double = 12,
                    .optional_bool = 13,
                    .optional_string = 14,
                    .optional_bytes = 15,
                    .optional_nested_message = 18,
                    .optional_foreign_message = 19,
                    .optional_nested_enum = 21,
                    .optional_foreign_enum = 22,
                    .optional_aliased_enum = 23,
                    .optional_string_piece = 24,
                    .optional_cord = 25,
                    .recursive_message = 27,
                    .repeated_int32 = 31,
                    .repeated_int64 = 32,
                    .repeated_uint32 = 33,
                    .repeated_uint64 = 34,
                    .repeated_sint32 = 35,
                    .repeated_sint64 = 36,
                    .repeated_fixed32 = 37,
                    .repeated_fixed64 = 38,
                    .repeated_sfixed32 = 39,
                    .repeated_sfixed64 = 40,
                    .repeated_float = 41,
                    .repeated_double = 42,
                    .repeated_bool = 43,
                    .repeated_string = 44,
                    .repeated_bytes = 45,
                    .repeated_nested_message = 48,
                    .repeated_foreign_message = 49,
                    .repeated_nested_enum = 51,
                    .repeated_foreign_enum = 52,
                    .repeated_string_piece = 54,
                    .repeated_cord = 55,
                    .packed_int32 = 75,
                    .packed_int64 = 76,
                    .packed_uint32 = 77,
                    .packed_uint64 = 78,
                    .packed_sint32 = 79,
                    .packed_sint64 = 80,
                    .packed_fixed32 = 81,
                    .packed_fixed64 = 82,
                    .packed_sfixed32 = 83,
                    .packed_sfixed64 = 84,
                    .packed_float = 85,
                    .packed_double = 86,
                    .packed_bool = 87,
                    .packed_nested_enum = 88,
                    .unpacked_int32 = 89,
                    .unpacked_int64 = 90,
                    .unpacked_uint32 = 91,
                    .unpacked_uint64 = 92,
                    .unpacked_sint32 = 93,
                    .unpacked_sint64 = 94,
                    .unpacked_fixed32 = 95,
                    .unpacked_fixed64 = 96,
                    .unpacked_sfixed32 = 97,
                    .unpacked_sfixed64 = 98,
                    .unpacked_float = 99,
                    .unpacked_double = 100,
                    .unpacked_bool = 101,
                    .unpacked_nested_enum = 102,
                    .optional_bool_wrapper = 201,
                    .optional_int32_wrapper = 202,
                    .optional_int64_wrapper = 203,
                    .optional_uint32_wrapper = 204,
                    .optional_uint64_wrapper = 205,
                    .optional_float_wrapper = 206,
                    .optional_double_wrapper = 207,
                    .optional_string_wrapper = 208,
                    .optional_bytes_wrapper = 209,
                    .repeated_bool_wrapper = 211,
                    .repeated_int32_wrapper = 212,
                    .repeated_int64_wrapper = 213,
                    .repeated_uint32_wrapper = 214,
                    .repeated_uint64_wrapper = 215,
                    .repeated_float_wrapper = 216,
                    .repeated_double_wrapper = 217,
                    .repeated_string_wrapper = 218,
                    .repeated_bytes_wrapper = 219,
                    .optional_duration = 301,
                    .optional_timestamp = 302,
                    .optional_field_mask = 303,
                    .optional_struct = 304,
                    .optional_any = 305,
                    .optional_value = 306,
                    .optional_null_value = 307,
                    .repeated_duration = 311,
                    .repeated_timestamp = 312,
                    .repeated_fieldmask = 313,
                    .repeated_struct = 324,
                    .repeated_any = 315,
                    .repeated_value = 316,
                    .repeated_list_value = 317,
                    .fieldname1 = 401,
                    .field_name2 = 402,
                    ._field_name3 = 403,
                    .field__name4_ = 404,
                    .field0name5 = 405,
                    .field_0_name6 = 406,
                    .fieldName7 = 407,
                    .FieldName8 = 408,
                    .field_Name9 = 409,
                    .Field_Name10 = 410,
                    .FIELD_NAME11 = 411,
                    .FIELD_name12 = 412,
                    .__field_name13 = 413,
                    .__Field_name14 = 414,
                    .field__name15 = 415,
                    .field__Name16 = 416,
                    .field_name17__ = 417,
                    .Field_name18__ = 418,
                },
            };

            pub const NestedMessage = struct {
                pub const protobuf_metadata = .{
                    .syntax = .proto3,
                    .field_numbers = .{
                        .a = 1,
                        .corecursive = 2,
                    },
                };

                a: i32 = 0,
                corecursive: protobuf_test_messages.proto3.TestAllTypesProto3 = .{},
            };

            pub const NestedEnum = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto3,
                };

                FOO = 0,
                BAR = 1,
                BAZ = 2,
                NEG = -1,
            };

            pub const AliasedEnum = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto3,
                };

                ALIAS_FOO = 0,
                ALIAS_BAR = 1,
                ALIAS_BAZ = 2,
                MOO = 2,
                moo = 2,
                bAz = 2,
            };

            optional_int32: i32 = 0,
            optional_int64: i64 = 0,
            optional_uint32: u32 = 0,
            optional_uint64: u64 = 0,
            optional_sint32: i32 = 0,
            optional_sint64: i64 = 0,
            optional_fixed32: u32 = 0,
            optional_fixed64: u64 = 0,
            optional_sfixed32: i32 = 0,
            optional_sfixed64: i64 = 0,
            optional_float: f32 = 0,
            optional_double: f64 = 0,
            optional_bool: bool = false,
            optional_string: []const u8 = "",
            optional_bytes: []const u8 = "",
            optional_nested_message: protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage = .{},
            optional_foreign_message: protobuf_test_messages.proto3.ForeignMessage = .{},
            optional_nested_enum: protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum = @enumFromInt(0),
            optional_foreign_enum: protobuf_test_messages.proto3.ForeignEnum = @enumFromInt(0),
            optional_aliased_enum: protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum = @enumFromInt(0),
            optional_string_piece: []const u8 = "",
            optional_cord: []const u8 = "",
            recursive_message: protobuf_test_messages.proto3.TestAllTypesProto3 = .{},
            repeated_int32: std.ArrayListUnmanaged(i32) = .{},
            repeated_int64: std.ArrayListUnmanaged(i64) = .{},
            repeated_uint32: std.ArrayListUnmanaged(u32) = .{},
            repeated_uint64: std.ArrayListUnmanaged(u64) = .{},
            repeated_sint32: std.ArrayListUnmanaged(i32) = .{},
            repeated_sint64: std.ArrayListUnmanaged(i64) = .{},
            repeated_fixed32: std.ArrayListUnmanaged(u32) = .{},
            repeated_fixed64: std.ArrayListUnmanaged(u64) = .{},
            repeated_sfixed32: std.ArrayListUnmanaged(i32) = .{},
            repeated_sfixed64: std.ArrayListUnmanaged(i64) = .{},
            repeated_float: std.ArrayListUnmanaged(f32) = .{},
            repeated_double: std.ArrayListUnmanaged(f64) = .{},
            repeated_bool: std.ArrayListUnmanaged(bool) = .{},
            repeated_string: std.ArrayListUnmanaged([]const u8) = .{},
            repeated_bytes: std.ArrayListUnmanaged([]const u8) = .{},
            repeated_nested_message: std.ArrayListUnmanaged(protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage) = .{},
            repeated_foreign_message: std.ArrayListUnmanaged(protobuf_test_messages.proto3.ForeignMessage) = .{},
            repeated_nested_enum: std.ArrayListUnmanaged(protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum) = .{},
            repeated_foreign_enum: std.ArrayListUnmanaged(protobuf_test_messages.proto3.ForeignEnum) = .{},
            repeated_string_piece: std.ArrayListUnmanaged([]const u8) = .{},
            repeated_cord: std.ArrayListUnmanaged([]const u8) = .{},
            packed_int32: std.ArrayListUnmanaged(i32) = .{},
            packed_int64: std.ArrayListUnmanaged(i64) = .{},
            packed_uint32: std.ArrayListUnmanaged(u32) = .{},
            packed_uint64: std.ArrayListUnmanaged(u64) = .{},
            packed_sint32: std.ArrayListUnmanaged(i32) = .{},
            packed_sint64: std.ArrayListUnmanaged(i64) = .{},
            packed_fixed32: std.ArrayListUnmanaged(u32) = .{},
            packed_fixed64: std.ArrayListUnmanaged(u64) = .{},
            packed_sfixed32: std.ArrayListUnmanaged(i32) = .{},
            packed_sfixed64: std.ArrayListUnmanaged(i64) = .{},
            packed_float: std.ArrayListUnmanaged(f32) = .{},
            packed_double: std.ArrayListUnmanaged(f64) = .{},
            packed_bool: std.ArrayListUnmanaged(bool) = .{},
            packed_nested_enum: std.ArrayListUnmanaged(protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum) = .{},
            unpacked_int32: std.ArrayListUnmanaged(i32) = .{},
            unpacked_int64: std.ArrayListUnmanaged(i64) = .{},
            unpacked_uint32: std.ArrayListUnmanaged(u32) = .{},
            unpacked_uint64: std.ArrayListUnmanaged(u64) = .{},
            unpacked_sint32: std.ArrayListUnmanaged(i32) = .{},
            unpacked_sint64: std.ArrayListUnmanaged(i64) = .{},
            unpacked_fixed32: std.ArrayListUnmanaged(u32) = .{},
            unpacked_fixed64: std.ArrayListUnmanaged(u64) = .{},
            unpacked_sfixed32: std.ArrayListUnmanaged(i32) = .{},
            unpacked_sfixed64: std.ArrayListUnmanaged(i64) = .{},
            unpacked_float: std.ArrayListUnmanaged(f32) = .{},
            unpacked_double: std.ArrayListUnmanaged(f64) = .{},
            unpacked_bool: std.ArrayListUnmanaged(bool) = .{},
            unpacked_nested_enum: std.ArrayListUnmanaged(protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum) = .{},
            map_int32_int32: std.AutoArrayHashMapUnmanaged(i32, i32) = .{},
            map_int64_int64: std.AutoArrayHashMapUnmanaged(i64, i64) = .{},
            map_uint32_uint32: std.AutoArrayHashMapUnmanaged(u32, u32) = .{},
            map_uint64_uint64: std.AutoArrayHashMapUnmanaged(u64, u64) = .{},
            map_sint32_sint32: std.AutoArrayHashMapUnmanaged(i32, i32) = .{},
            map_sint64_sint64: std.AutoArrayHashMapUnmanaged(i64, i64) = .{},
            map_fixed32_fixed32: std.AutoArrayHashMapUnmanaged(u32, u32) = .{},
            map_fixed64_fixed64: std.AutoArrayHashMapUnmanaged(u64, u64) = .{},
            map_sfixed32_sfixed32: std.AutoArrayHashMapUnmanaged(i32, i32) = .{},
            map_sfixed64_sfixed64: std.AutoArrayHashMapUnmanaged(i64, i64) = .{},
            map_int32_float: std.AutoArrayHashMapUnmanaged(i32, f32) = .{},
            map_int32_double: std.AutoArrayHashMapUnmanaged(i32, f64) = .{},
            map_bool_bool: std.AutoArrayHashMapUnmanaged(bool, bool) = .{},
            map_string_string: std.AutoArrayHashMapUnmanaged([]const u8, []const u8) = .{},
            map_string_bytes: std.AutoArrayHashMapUnmanaged([]const u8, []const u8) = .{},
            map_string_nested_message: std.AutoArrayHashMapUnmanaged([]const u8, protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage) = .{},
            map_string_foreign_message: std.AutoArrayHashMapUnmanaged([]const u8, protobuf_test_messages.proto3.ForeignMessage) = .{},
            map_string_nested_enum: std.AutoArrayHashMapUnmanaged([]const u8, protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum) = .{},
            map_string_foreign_enum: std.AutoArrayHashMapUnmanaged([]const u8, protobuf_test_messages.proto3.ForeignEnum) = .{},
            optional_bool_wrapper: google.protobuf.BoolValue = .{},
            optional_int32_wrapper: google.protobuf.Int32Value = .{},
            optional_int64_wrapper: google.protobuf.Int64Value = .{},
            optional_uint32_wrapper: google.protobuf.UInt32Value = .{},
            optional_uint64_wrapper: google.protobuf.UInt64Value = .{},
            optional_float_wrapper: google.protobuf.FloatValue = .{},
            optional_double_wrapper: google.protobuf.DoubleValue = .{},
            optional_string_wrapper: google.protobuf.StringValue = .{},
            optional_bytes_wrapper: google.protobuf.BytesValue = .{},
            repeated_bool_wrapper: std.ArrayListUnmanaged(google.protobuf.BoolValue) = .{},
            repeated_int32_wrapper: std.ArrayListUnmanaged(google.protobuf.Int32Value) = .{},
            repeated_int64_wrapper: std.ArrayListUnmanaged(google.protobuf.Int64Value) = .{},
            repeated_uint32_wrapper: std.ArrayListUnmanaged(google.protobuf.UInt32Value) = .{},
            repeated_uint64_wrapper: std.ArrayListUnmanaged(google.protobuf.UInt64Value) = .{},
            repeated_float_wrapper: std.ArrayListUnmanaged(google.protobuf.FloatValue) = .{},
            repeated_double_wrapper: std.ArrayListUnmanaged(google.protobuf.DoubleValue) = .{},
            repeated_string_wrapper: std.ArrayListUnmanaged(google.protobuf.StringValue) = .{},
            repeated_bytes_wrapper: std.ArrayListUnmanaged(google.protobuf.BytesValue) = .{},
            optional_duration: google.protobuf.Duration = .{},
            optional_timestamp: google.protobuf.Timestamp = .{},
            optional_field_mask: google.protobuf.FieldMask = .{},
            optional_struct: google.protobuf.Struct = .{},
            optional_any: google.protobuf.Any = .{},
            optional_value: google.protobuf.Value = .{},
            optional_null_value: google.protobuf.NullValue = @enumFromInt(0),
            repeated_duration: std.ArrayListUnmanaged(google.protobuf.Duration) = .{},
            repeated_timestamp: std.ArrayListUnmanaged(google.protobuf.Timestamp) = .{},
            repeated_fieldmask: std.ArrayListUnmanaged(google.protobuf.FieldMask) = .{},
            repeated_struct: std.ArrayListUnmanaged(google.protobuf.Struct) = .{},
            repeated_any: std.ArrayListUnmanaged(google.protobuf.Any) = .{},
            repeated_value: std.ArrayListUnmanaged(google.protobuf.Value) = .{},
            repeated_list_value: std.ArrayListUnmanaged(google.protobuf.ListValue) = .{},
            fieldname1: i32 = 0,
            field_name2: i32 = 0,
            _field_name3: i32 = 0,
            field__name4_: i32 = 0,
            field0name5: i32 = 0,
            field_0_name6: i32 = 0,
            fieldName7: i32 = 0,
            FieldName8: i32 = 0,
            field_Name9: i32 = 0,
            Field_Name10: i32 = 0,
            FIELD_NAME11: i32 = 0,
            FIELD_name12: i32 = 0,
            __field_name13: i32 = 0,
            __Field_name14: i32 = 0,
            field__name15: i32 = 0,
            field__Name16: i32 = 0,
            field_name17__: i32 = 0,
            Field_name18__: i32 = 0,
        };

        pub const ForeignMessage = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{
                    .c = 1,
                },
            };

            c: i32 = 0,
        };

        pub const ForeignEnum = enum(i32) {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
            };

            FOREIGN_FOO = 0,
            FOREIGN_BAR = 1,
            FOREIGN_BAZ = 2,
        };

        pub const NullHypothesisProto3 = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{},
            };
        };

        pub const EnumOnlyProto3 = struct {
            pub const protobuf_metadata = .{
                .syntax = .proto3,
                .field_numbers = .{},
            };

            pub const Bool = enum(i32) {
                pub const protobuf_metadata = .{
                    .syntax = .proto3,
                };

                kFalse = 0,
                kTrue = 1,
            };
        };
    };
};
